# Generated by Django 2.1.7 on 2020-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Residence', models.CharField(max_length=20)),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(default='', max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('Pincode', models.CharField(max_length=6)),
                ('State', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=25)),
                ('EmailId', models.CharField(max_length=50)),
                ('MobileNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('TenthStatus', models.CharField(max_length=5)),
                ('TenthYear', models.IntegerField()),
                ('TenthBoard', models.CharField(max_length=10)),
                ('TenthRollNo', models.CharField(max_length=7)),
                ('TenthResultMode', models.CharField(max_length=15)),
                ('TenthResult', models.CharField(max_length=6)),
                ('TwelfthStatus', models.CharField(max_length=5)),
                ('TwelfthYear', models.IntegerField()),
                ('TwelfthBoard', models.CharField(max_length=10)),
                ('TwelfthRollNo', models.CharField(max_length=7)),
                ('TwelfthResultMode', models.CharField(max_length=15)),
                ('TwelfthResult', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ManagerId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('AppId', models.CharField(default='SOME STRING', max_length=12, primary_key=True, serialize=False)),
                ('Fees', models.IntegerField(null=True)),
                ('TxId', models.CharField(max_length=50, null=True)),
                ('DateOfSubmission', models.DateField(null=True)),
                ('DateOfTx', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=500)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('MotherName', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=9)),
                ('Rollno', models.CharField(max_length=8)),
                ('Category', models.CharField(max_length=10)),
                ('PwdStatus', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=8)),
                ('SecureQue', models.CharField(max_length=500)),
                ('SecureAns', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('CorrectAns', models.IntegerField()),
                ('IncorrectAns', models.IntegerField()),
                ('Result', models.CharField(max_length=3)),
                ('Rank', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('AppId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Photo', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('Signature', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
